version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: ./workspaces/api/Dockerfile
    restart: always
    deploy:
      replicas: 4
  frontend:
    build:
      context: .
      dockerfile: ./workspaces/frontend/Dockerfile
    restart: always
    deploy:
      replicas: 2
  content:
    build:
      context: .
      dockerfile: ./workspaces/content/Dockerfile
    restart: always
    deploy:
      replicas: 4
  proxy:
    build:
      context: .
      dockerfile: ./workspaces/proxy/Dockerfile
    restart: always
    ports:
      - 80:80